set nocompatible

filetype plugin indent on

set autoread
set autowrite

syntax on

set number
set relativenumber
set backspace=indent,eol,start
set expandtab
set softtabstop=4
set shiftwidth=4
set autoindent

set undofile
set undodir=~/.vimtmp/undo
silent !mkdir -p ~/.vimtmp/undo

set scrolloff=5

set cursorline
match Error "\s\+$"

set mouse=a

set completeopt=menu,longest

set visualbell

colorscheme slate
set background=dark

set list listchars=tab:»·,trail:·

" Clearing PAGER var to use vim as MANPAGER
let PAGER=''
